server:
  port: 8082
management:
  server:
    port: 9082
spring:
  main:
    web-application-type: reactive
  application:
    name: media-service
  webflux:
    base-path: /media
  config:
    import:
      - 'classpath:config/liquibase.yml'
      - 'classpath:config/r2dbc.yml'
      - 'classpath:config/oauth2.yml'
      - 'classpath:config/eureka-client.yml'
      - 'classpath:config/springdoc.yml'
      - 'classpath:management.yml'
  http:
    codecs:
      max-in-memory-size: 10MB

logging:
  config: classpath:log4j2-spring.xml
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG
